### PR TITLE
289 unit contract map fixes

### LINKED ISSUE #289: Update procurementUnitMap when inspection period changes (0,5d)
When changing the inspection period of a pre-inspection, the procurement unit => contract map does not update. This leads to problems when trying to find contracts for procurement units. The map may also be left un-updated in other cases.

Further, no errors are shown when the map is not updated.

Tasks:

- Show validation error when the map does not match the inspection period.
- Automatically update the map as needed
- Test that contracts are found for all units after inspection period is updated.

### PR DESCRIPTION
**Pull request by danieldunderfelt**
Closes #289 

UI PR: https://github.com/HSLdevcom/bultti-ui/pull/98

Update procurement unit contract map feature so that the map updates when the inspection is updated. Also generate a new map instead of clearing it when the inspection is rejected. New contract validation checks are also added.

This PR also fixes an issue where post-inspection data is not removed when rejecting it that I noticed along the way.

### CODE REVIEW

File: src/inspection/validateInspection.ts [hunk 1]
```diff
@@ -14,45 +14,63 @@ import { PreInspection } from './PreInspectionEntity'
...
+      type: InspectionValidationError.MISSING_CONTRACTS,
+      keys: ['contract'],
+      objectId: inspection.id,
+    })
+  }
+
+  let contractMapIds = uniq(Object.values(inspection.procurementUnitContractMap || {}))
+
+  // Validate that the contracts in the map are valid for the inspection period.
+  if (!validateContractsForInspectionDate(date, contractMapIds)) {
```
Comment (Divinare) [inline src/inspection/validateInspection.ts:38]: This one is pretty smart validation. Isn't it so that if an inspection is made, the contract dates can still made until the preInspection is being put to IN_PRODUCTION. Now this validation ensures that the contracts are still within inspection date range.

File: src/inspection/validateInspection.ts [hunk 2]
```diff
@@ -161,6 +180,39 @@ export async function validatePostInspection(
...
+  let isValid = true
+  let contractRepo = getRepository(Contract)
+  let dateObj = getDateObject(inspectionStartDate)
+
+  for (let contractId of contractIds) {
+    let contract = await contractRepo.findOneOrFail(contractId)
+
+    isValid = isWithinInterval(dateObj, {
+      start: getDateObject(contract.startDate),
+      end: getDateObject(contract.endDate),
```
Comment (Divinare) [inline src/inspection/validateInspection.ts:205]: Shouldnt it be like this:
```
let checkInterval = { start: inspectionStartDate, end: inspectionEndDate }

    return areIntervalsOverlapping(checkInterval, {
      start: getDateObject(contract.startDate),
      end: getDateObject(contract.endDate),
    })

```

Contract is OK if it overlaps inspectionStartDate - inspectionEndDate time range?

**Review by Divinare — CHANGES_REQUESTED** [review]
Left some comments, havent tested yet

File: src/inspection/validateInspection.ts [hunk 3]
```diff
@@ -14,45 +14,63 @@ import { PreInspection } from './PreInspectionEntity'
...
   for (let unit of procurementUnits) {
-    if (!unit.currentContracts || unit.currentContracts.length === 0) {
+    let currentContracts = unit.currentContracts || []
+    let unitAssignedContract = unitContractMap[unit.id]
+
+    // Check that the contract assigned to this unit in the contract unit map is among
+    // the currentContracts (which are the currently valid contracts) of this unit.
+    let assignedContractIsValidForUnit =
+      unitAssignedContract &&
+      currentContracts.some(contract => contract.id === unitAssignedContract)
```
[the remark this answers is not in the document]
Comment (danieldunderfelt) [reply src/inspection/validateInspection.ts:64]: Indeed this should not happen, but it may if the contractUnitMap gets out of sync somehow. Not that I have noticed it!

File: src/inspection/validateInspection.ts (hunk 2 above)
Comment (danieldunderfelt) [reply src/inspection/validateInspection.ts:205]: Pre-inspection periods are one week, and the contract can't change in the middle of the week. So if we check the start of the inspection week, it is enough!

Post-inspection dates are not checked with this since they get their inspections through their linked pre-inspections.

File: src/procurementUnit/procurementUnitUtils.ts [hunk 4]
```diff
@@ -15,25 +15,33 @@ import { Inspection } from '../inspection/InspectionEntity'
...
 export async function getProcurementUnitsByOperator({
   operatorId,
   startDate,
   endDate,
+  refreshUnitsFromJore = true,
 }: {
   operatorId: number
   startDate: string
   endDate: string
+  refreshUnitsFromJore?: boolean
```
[the remark this answers is not in the document]
Comment (danieldunderfelt) [reply src/procurementUnit/procurementUnitUtils.ts:39]: This isn't, but the `getProcurementUnitsByInspection` function above is called with false!

I really dislike using "should", it sounds like a test assertion. I almost used it here, but it feels like nails on a chalkboard for me. is/has/ etc is fine.

File: src/inspection/CommonInspectionResolver.ts [hunk 5]
```diff
@@ -310,11 +310,12 @@ export class CommonInspectionResolver
     draftInspection.versionStackIdentifier = stackIdentifier
 
     let seasonStart = parseISO(season.startDate)
+
     let currentProdStart = currentProduction?.startDate
       ? parseISO(currentProduction.startDate)
       : seasonStart
 
-    draftInspection.minStartDate = getDateString(seasonStart)
+    draftInspection.minStartDate = getDateString(max([seasonStart, currentProdStart]))
```
[the remark this answers is not in the document]
Comment (danieldunderfelt) [reply src/inspection/CommonInspectionResolver.ts:318]: Probably some test change that was mistakenly left in. We did talk about this on Slack...

File: src/inspection/validateInspection.ts (hunk 2 above)
Comment (Divinare) [reply src/inspection/validateInspection.ts:199]: Added a comment about this that the method currently only supports preInspections just to highlight that it can't be used for postInspections

Maybe we should have separate files for pre and post inspections to make more clear which method is common, which one is for only pre/postInspectons

**Comment by Divinare** [comment]
Tested that inspections now lock contracts and contract procurementUnits properly!

**Review by Divinare — APPROVED** [review]
