### PR TITLE
100 exception days

### LINKED ISSUE #100: Exception dates in inspections
Take exception dates into account in inspections.

- Query for exception schema departures
- Use normal block departures if no exception block departures are found.

### PR DESCRIPTION
**Pull request by danieldunderfelt**
Use exception days in JORE departure queries. Closes #100.

Also, some changes to observed departures which are being continued in future PR's, but were needed for testing the exception day changes here.

### CODE REVIEW

File: src/departure/createObservedDeparturesTask.ts [hunk 1]
```diff
@@ -22,13 +22,13 @@ import { logTime } from '../util/logTime'
...
-export async function createObservedDepartures({
+export async function createObservedDeparturesTask({
   inspectionId,
   cacheKey,
 }: {
   inspectionId: string
-  cacheKey: string
-}) {
+  cacheKey?: string
+}): Promise<void | ObservedDeparture[]> {
```
Comment (Divinare) [inline src/departure/createObservedDeparturesTask.ts:31]: I would just make return type as "ObservedDeparture[]", return empty array if nothing was created

File: src/departure/createObservedDeparturesTask.ts [hunk 2]
```diff
@@ -301,5 +268,9 @@ export async function createObservedDepartures({
   logTime('Departures created', time)
   let allObservedDepartures = flatten(observedDepartures)
 
-  await setItem(cacheKey, allObservedDepartures, 5 * 24 * 60 * 60)
+  if (cacheKey) {
+    await setItem(cacheKey, allObservedDepartures, 5 * 24 * 60 * 60)
```
Comment (Divinare) [inline src/departure/createObservedDeparturesTask.ts:272]: Could be renamed as "setCacheItem" or "cacheSet"

**Review by Divinare — COMMENTED** [review]
Added some review comments, didn't test these changes though. Can be merged after possibly fixing those.

File: src/departure/analyzeObservedDepartures.ts [hunk 3]
```diff
@@ -254,6 +212,8 @@ export async function createObservedDepartures(inspection: Inspection) {
     `${inspection.inspectionStartDate}_${inspection.inspectionEndDate}_${inspection.operatorId}`
   )
 
+  // let result = await createObservedDeparturesTask({ inspectionId: inspection.id })
```
[the remark this answers is not in the document]
Comment (danieldunderfelt) [reply src/departure/analyzeObservedDepartures.ts:215]: No, this is for development if I don't want to run the task on the worker. Then I comment the thing above and uncomment this. I still need it, so no use in removing it.

File: src/departure/createObservedDeparturesTask.ts (hunk 1 above)
Comment (danieldunderfelt) [reply src/departure/createObservedDeparturesTask.ts:31]: I would too, but not returning anything signals to the queue that the task doesn't return anything and it won't try to put the return value into Redis. Since the function puts the result of the task into Redis itself, this is how we want it to work.

When running the task on the main server (ie not on the worker) we WANT to return the result to the caller of the task.

File: src/departure/createObservedDeparturesTask.ts (hunk 2 above)
Comment (danieldunderfelt) [reply src/departure/createObservedDeparturesTask.ts:272]: Yes, I am not opposed to this. But it is out of the scope of this PR.

File: src/departure/createObservedDeparturesTask.ts (hunk 1 above)
Comment (Divinare) [reply src/departure/createObservedDeparturesTask.ts:31]: I think createObservedDeparturesTask() shouldn't know anything about how Redis works

If needed some specific logic I would put it in runTasks e.g.

```
const runTask = (createFunction: function) => {
    const result = createFunction()
    /** Redis requires undefined not empty array*/
    if (Array.isArray(result) && result.length === 0) {
         return undefined;
    }
}


export const runTasks = {
  CreateObservedDepartures: runTask(createObservedDeparturesTask),
}

```

Off topic: also would it be a good idea to put all worker related code under /worker folder?

File: src/departure/analyzeObservedDepartures.ts (hunk 3 above)
[the remark this answers is not in the document]
Comment (Divinare) [reply src/departure/analyzeObservedDepartures.ts:215]: That's fine. Usually I leave "// For development" in these cases to remind others the purpose of it

File: src/departure/createObservedDeparturesTask.ts (hunk 1 above)
Comment (danieldunderfelt) [reply src/departure/createObservedDeparturesTask.ts:31]: That's actually a good idea! I'm not opposed to the task knowing how Redis works but that solution is nice.

The worker folder contains only files specific to the separate Worker server instances. We have the /queue folder where the task configuration lives. And the tasks themselves belong to the feature package.
